---
dependencies: []

galaxy_info:
  role_name: package_manager_configuration
  namespace: ccdc
  author: rockdreamer
  description: Set up package managers and CCDC artifactory repositories.
  company: The Cambridge Crystallographic Data Centre
  license: "license (BSD, MIT)"
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: MacOSX
      versions:
        - all
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - system
