---
# Modern clang on centos7? Why not!
- name: Add llvm-toolset-10 repository from cloudlinux
  ansible.builtin.yum_repository:
    name: cloudlinux-llvm-toolset-10.0
    description: llvm-toolset-10 repository from cloudlinux
    # mirror of https://repo.cloudlinux.com/cloudlinux/7/sclo/llvm-toolset-10.0
    baseurl: https://artifactory.ccdc.cam.ac.uk/artifactory/public-cloudlinux-llvm-toolset-10.0/
    gpgcheck: false
    username: "{{ ansible_deployment_artifactory_user }}"
    password: "{{ ansible_deployment_artifactory_key }}"
  become: true

- name: Add oracle linux 7's ol7_software_collections repository
  ansible.builtin.yum_repository:
    name: ol7_software_collections
    description: ol7_software_collections
    # mirror of http://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64/
    baseurl: https://artifactory.ccdc.cam.ac.uk/artifactory/public-ol7-scl/
    gpgcheck: false
    username: "{{ ansible_deployment_artifactory_user }}"
    password: "{{ ansible_deployment_artifactory_key }}"
  become: true

- name: Add EPEL repository from artifactory
  ansible.builtin.yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://artifactory.ccdc.cam.ac.uk/artifactory/public-epel-7-mirror/
    gpgkey: https://artifactory.ccdc.cam.ac.uk/artifactory/ccdc-3rd-party-sources/RPM-GPG-KEY-EPEL-7
    username: "{{ ansible_deployment_artifactory_user }}"
    password: "{{ ansible_deployment_artifactory_key }}"
  become: true

# Centos7 requires the scl package to enable fetching packages from software collections
- name: Install software collections
  ansible.builtin.package:
    name:
      - centos-release-scl
    state: present
  become: true
